# Generated by Django 6.0.6 on 2026-06-12 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('breed', models.CharField(default='Mestizo', max_length=100, verbose_name='Raza')),
                ('age_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Edad (meses)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PENDING', 'En Proceso'), ('ADOPTED', 'Adoptado')], default='AVAILABLE', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Especie')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('motivation', models.TextField(verbose_name='¿Por qué desea adoptar?')),
                ('status', models.CharField(choices=[('REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='REVIEW', max_length=10, verbose_name='Estado de la Solicitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelter.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Solicitud de Adopción',
                'verbose_name_plural': 'Solicitudes de Adopción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='shelter.species', verbose_name='Especie'),
        ),
    ]
